### ISSUE TITLE
Benchmarking data for aggregator mode.

### ISSUE THREAD

**Issue by niedbalski** [calyptia/benchmarking#6]
### From the latest (08/11/2022) sync on benchmarking.

For the aggregator mode, we will focus on consolidating the benchmark data into our
public grafana instance. Also, we'll just measure tail_forward (for input instances) and tcp_null (for aggregator instance).

- [x] Create a single script that can parametrise a benchmark run.

1. Amount of input forwarder VM(s).
2. The machine type of the aggregator VM.
3. Input instances data rate  (that's per the load generator script rate / sec ). 
4. Duration time of the benchmark run.

- [ ] Capture the calyptia-cloud API metrics for bytes / records and error rate for agents on Grafana. (Use @Chieze-Franklin's data source plugin).
- [x] Capture the node-exporter metrics to the prometheus push gateway at Grafana. 
- [x] Create a single dashboard in the public Grafana (grafana.calyptia.com) (Benchmarking / Aggregator view)
- [ ] Create a single graph that can display Throughput per CPU core (Bytes processed / CPU cores).

**Comment by patrick-stephens** [comment]
@niedbalski do we need a new Grafana Cloud project for this? It probably makes sense to isolate it a bit, and control that creation maybe in Terraform: possibly here or in our infra repo but if we have it here we can include the dashboards, etc. too.

**Comment by niedbalski** [comment]
> @niedbalski do we need a new Grafana Cloud project for this? It probably makes sense to isolate it a bit, and control that creation maybe in Terraform: possibly here or in our infra repo but if we have it here we can include the dashboards, etc. too.

+1

**Comment by patrick-stephens** [comment]
I think I'll add a monitoring stack to the aggregator VM as well if only to help iterate the dashboards, it also means people can see everything in their own instances if they want.

**Comment by patrick-stephens** [comment]
I've created a new stack: https://calyptiabenchmarks.grafana.net/
